spring:
  application:
    name: notion
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  flyway:
    enabled: true
    baseline-on-migrate: true

# MinIO (S3) configuration
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: my-bucket
server:
  port: 8080
